In [1]:
import numpy as np
import cv2
import sys

In [2]:
cv2.namedWindow("tracking")
camera = cv2.VideoCapture(0)
tracker = cv2.MultiTracker_create()
init_once = False
ok, image = camera.read()
if not ok:
    print("Failed to read video")
    exit()

bbox1 = cv2.selectROI('tracking', image)
bbox2 = cv2.selectROI('tracking', image)
bbox3 = cv2.selectROI('tracking', image)
print(type(bbox1))
print(bbox1)
while True:
    ok, image = camera.read()
    if not ok:
        print("No image to read")
        break
    
    if not init_once:
        ok = tracker.add(cv2.TrackerMIL_create(), image, bbox1)
        ok = tracker.add(cv2.TrackerMIL_create(), image, bbox2)
        ok = tracker.add(cv2.TrackerMIL_create(), image, bbox3)
        
        init_once = True
        
    ok, boxes = tracker.update(image)
    print(boxes)
    print(type(boxes))
    print(ok, boxes)
    
    for newbox in boxes:
        p1 = (int(newbox[0]), int(newbox[1]))
        p2 = (int(newbox[0] + newbox[2]), int(newbox[1] + newbox[3]))
        cv2.rectangle(image, p1, p2, (200, 0, 0))
        
    cv2.imshow("image", image)
    
    # Check for key strokes
    k = cv2.waitKey(1) & 0xff
    if k == ord('n'):
        continue
    elif k == 27:  # 'esc' key has been pressed, exit program.
        break
cap.release()
cv2.destroyAllWindows()           


<class 'tuple'>
(311, 25, 215, 246)
[[311.  25. 215. 246.]
 [ 19.  48.  91. 151.]
 [ 62. 257. 165. 180.]]
<class 'numpy.ndarray'>
True [[311.  25. 215. 246.]
 [ 19.  48.  91. 151.]
 [ 62. 257. 165. 180.]]
[[312.  25. 215. 246.]
 [ 19.  48.  91. 151.]
 [ 62. 257. 165. 180.]]
<class 'numpy.ndarray'>
True [[312.  25. 215. 246.]
 [ 19.  48.  91. 151.]
 [ 62. 257. 165. 180.]]
[[314.  24. 215. 246.]
 [ 18.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[314.  24. 215. 246.]
 [ 18.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[316.  23. 215. 246.]
 [ 18.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[316.  23. 215. 246.]
 [ 18.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[306.  27. 215. 246.]
 [ 19.  49.  91. 151.]
 [ 64. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[306.  27. 215. 246.]
 [ 19.  49.  91. 151.]
 [ 64. 258. 165. 180.]]
[[306.  27. 215. 246.]
 [ 18.  48.  91. 151.]
 [ 63. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[306.  27. 215. 246

[[262.  36. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[262.  36. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[264.  36. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[264.  36. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[265.  37. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[265.  37. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[265.  37. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[265.  37. 215. 246.]
 [ 16.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
[[265.  35. 215. 246.]
 [ 16.  49.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[265.  35. 215. 246.]
 [ 16.  49.  91. 151.]
 [ 62. 258. 165. 180.]]
[[265.  34. 215. 246.]
 [ 17.  48.  91. 151.]
 [ 62. 258. 165. 180.]]
<class 'numpy.ndarray'>
True [[265.  34. 215. 246.]
 [ 17.  48.  91. 151.]
 [ 62. 258

KeyboardInterrupt: 

In [ ]:

import numpy as np
import cv2 as cv
import sys

if len(sys.argv) != 2:
    print('Input video name is missing')
    exit()

cv.namedWindow("tracking")
camera = cv.VideoCapture(0)
ok, image=camera.read()
if not ok:
    print('Failed to read video')
    exit()
bbox = cv.selectROI("tracking", image)
tracker = cv.TrackerMIL_create()
init_once = False

while camera.isOpened():
    ok, image=camera.read()
    if not ok:
        print ('no image to read')
        break

    if not init_once:
        ok = tracker.init(image, bbox)
        init_once = True

    ok, newbox = tracker.update(image)
    print (ok, newbox)

    if ok:
        p1 = (int(newbox[0]), int(newbox[1]))
        p2 = (int(newbox[0] + newbox[2]), int(newbox[1] + newbox[3]))
        cv.rectangle(image, p1, p2, (200,0,0))

    cv.imshow("tracking", image)
    k = cv.waitKey(1) & 0xff
    if k == 27 : break # esc pressed